import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
    products: [
     
      {
        // _id: '1',
        name: 'Bangladeshi Taka 1880',
        slug: 'Bangladeshi Taka 1880',
        category: 'AncientMoney',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Bangladesh',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        // _id: '2',
        name: 'Argentine Peso 1910',
        slug: 'Argentina Peso 1910',
        category: 'AncientMoney',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 0,
        brand: 'Argentina',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        // _id: '3',
        name: 'Indian Rupi 1223',
        slug: 'Indian Rupi 1223',
        category: 'AncientCoin',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'India',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        // _id: '4',
        name: 'Japanies Yen 1200',
        slug: 'Japanies Yen 1200',
        category: 'AncientMoney',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Japan',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      // {
      //   // _id: '4',
      //   name: 'Japanies Yen 1200',
      //   slug: 'Japanies Yen 1200',
      //   category: 'Ancient-UsesGoods',
      //   image: '/images/p5.jpg',
      //   price: 65,
      //   countInStock: 5,
      //   brand: 'Japan',
      //   rating: 4.5,
      //   numReviews: 10,
      //   description: 'high quality product',
      // },
      // {
      //   // _id: '4',
      //   name: 'Japanies Yen 1200',
      //   slug: 'Japanies Yen 1200',
      //   category: 'Ancient-UsesGoods',
      //   image: '/images/p6.jpg',
      //   price: 65,
      //   countInStock: 5,
      //   brand: 'Japan',
      //   rating: 4.5,
      //   numReviews: 10,
      //   description: 'high quality product',
      // },
      // {
      //   // _id: '4',
      //   name: 'Japanies Yen 1200',
      //   slug: 'Japanies Yen 1200',
      //   category: 'Ancient-UsesGoods',
      //   image: '/images/p7.jpg',
      //   price: 65,
      //   countInStock: 5,
      //   brand: 'Japan',
      //   rating: 4.5,
      //   numReviews: 10,
      //   description: 'high quality product',
      // },
      // {
      //   // _id: '4',
      //   name: 'Japanies Yen 1200',
      //   slug: 'Japanies Yen 1200',
      //   category: 'Ancient-UsesGoods',
      //   image: '/images/p8.jpg',
      //   price: 65,
      //   countInStock: 5,
      //   brand: 'Japan',
      //   rating: 4.5,
      //   numReviews: 10,
      //   description: 'high quality product',
      // }
    ],
  };
  export default data;